### ISSUE TITLE
starter site development process

### ISSUE THREAD

**Issue by Natkeeran** [Islandora-Devops/islandora-starter-site#49] opened 2023-01-31 20:55 UTC
In the "General starter site development process" section, the fifth step is to copy the config/sync folder into the PR.  However, if the starter site  was deployed to a site url other than 127.0.0.1, then that can impact several config settings such as the one below

```
--- a/config/sync/search_api.server.default_solr_server.yml
+++ b/config/sync/search_api.server.default_solr_server.yml
@@ -42,7 +42,7 @@ backend_config:
   connector: standard
   connector_config:
     scheme: http
-    host: 127.0.0.1
+    host: 143.110.222.18
     port: 8983
     core: ISLANDORA
     timeout: 5
```
```
	modified:   config/sync/core.extension.yml
	modified:   config/sync/islandora.settings.yml
	modified:   config/sync/islandora_iiif.settings.yml
	modified:   config/sync/media.settings.yml
	modified:   config/sync/openseadragon.settings.yml
	modified:   config/sync/search_api.server.default_solr_server.yml
```

How can we handle this issue?  Should we pick the relevant config and check them into the config/sync folder?

**Comment by adam-vessey** [comment] 2023-02-01 18:32
Duplicate of #17? ... or perhaps #17 should be widened to include provisioning outside of Isle and Playbook?

**Comment by rosiel** [comment] 2023-02-07 21:46
This is a duplicate of #17.

**Closed by rosiel** 2023-02-07 21:46 UTC
