### ISSUE TITLE
[BUG] Video repository items are not showing the embedded viewer

### ISSUE THREAD

**Issue by nigelgbanks** [Islandora-Devops/islandora-starter-site#21] opened 2022-11-08 12:18 UTC
**What steps does it take to reproduce the issue?**

- Start up a site based on islandora-starter-pack
- Create a new Video repository item
- Set Resource Type to `Moving Image` (Not sure if this is required any more, but to be safe)
- Select `N/A` for the `Display Hint Field`
- Add a `Original File` /  `Preservation Master` video media entity to the repository item
- Note that it does not display on the repository item

---

* When does this issue occur?

When viewing a repository item.

* Which page does it occur on?

The view page for the repository item.

* What happens?

The video viewer does not display.

* To whom does it occur (anonymous visitor, editor, administrator)?

To all users regardless of role.

* What did you expect to happen?

The video viewer to display.

**Which version of Islandora are you using?**

2.4.3 (I was using https://github.com/Islandora/islandora-starter-site/commit/8a32258f3a564180fbc69a8a80c2c4c0f785ebd4 of this repository)

**Any related open or closed issues to this bug report?**

N/A

**Screenshots:**

Repository Item View Page:
![Screenshot 2022-11-08 at 12 12 01](https://user-images.githubusercontent.com/487373/200561689-7ec13b96-c46a-4747-88bd-0caa2cebc96c.png)

Media Items:

![Screenshot 2022-11-08 at 12 12 08](https://user-images.githubusercontent.com/487373/200561692-849f6660-2bb5-44f1-b43b-44f39e794996.png)

I can view the video on the browser by clicking the file link, no viewer display, though.

**Comment by rosiel** [comment] 2022-11-08 12:24
Yes! I think this is the issue of the [contexts which (since defaults) assumed bartik](https://github.com/Islandora/islandora-starter-site/issues/10).  Changing this was considered out of scope for the move to the starter site, and it's been high on my mind, but I haven't had a chance to fix it yet. :(

**Comment by rosiel** [comment] 2022-11-08 13:41
OOPS NOPE that's not it - though that's an outstanding issue, I think the problem is that Video is configured to show a Service File and **one's not being created**. Sorry! This could be the derivatives problem that @aOelschlager identified, which IIRC can be solved if using the [branch of Buildkit that uses a karaf-less Alpaca](https://github.com/Islandora-Devops/isle-buildkit/tree/issues-225-update-alpaca).

**Comment by rosiel** [comment] 2022-11-08 15:47
So... if you tag your existing file as a service file, does it display? 

I think the configs at play are:
* since you're not choosing a display hint (and starter site doesn't do as many contexts as the sandbox), you're on the default view mode
* core.entity_view_display.node.islandora_object.default.yml displays "[display_media_service_file](https://github.com/Islandora/islandora-starter-site/blob/8a32258f3a564180fbc69a8a80c2c4c0f785ebd4/config/sync/core.entity_view_display.node.islandora_object.default.yml#L63-L67)" 
* which is the [display_media view](https://github.com/Islandora/islandora-starter-site/blob/8a32258f3a564180fbc69a8a80c2c4c0f785ebd4/config/sync/views.view.display_media.yml)'s [service_file](https://github.com/Islandora/islandora-starter-site/blob/8a32258f3a564180fbc69a8a80c2c4c0f785ebd4/config/sync/views.view.display_media.yml#L357-L437) display

**Comment by nigelgbanks** [comment] 2022-11-09 11:59
The sandbox seems to show the embedded video player without a `Service File` tag. However, it does show if I add the `Service File` tag to the video.

**Comment by nigelgbanks** [comment] 2022-11-09 11:59
The sandbox also does not create a derivative, I should mention.

**Comment by rosiel** [comment] 2022-11-10 20:13
Sandbox is configured to create a Service File from an Original File. ([Action](https://sandbox.islandora.ca/admin/structure/context/video_original_file), [Context](https://sandbox.islandora.ca/admin/config/system/actions/configure/video_generate_a_service_file_from_an_original_file))
I can confirm that this did not happen for the video I uploaded.

Sandbox is [configured to show the Original File EVA](https://sandbox.islandora.ca/admin/structure/types/manage/islandora_object/display) on the default display mode. This is, AFAIK, a deviation from the Starter Site/Defaults.

**Comment by rosiel** [comment] 2022-12-09 14:47
Starter Site is configured to:
* create a service file video from an original file
* display the **service file** near the top of the page. It will show in the media's "source" view mode unless overridden by the view mode picker.
* display the **original file** as a download link with filesize and hash. 

What we haven't tackled is how to deal with times where you want to use the file you upload - the original file - _as_ the service file for the purpose of display on the node's page.

My suggestion is to double-tag (upload a file and mark it as "Original File" and "Service File".) This seems the most intuitive. However, I don't want to suggest this until I'm sure it wont cause infinite loops of derivatives. I think at the moment that it might. A simple "check to see if the destination term uri is on the source media and stop if it is" would suffice. I think there are open issues about this:
* https://github.com/Islandora/islandora/issues/903
* https://github.com/Islandora-Devops/isle-buildkit/issues/248

**Comment by rosiel** [comment] 2023-02-27 15:26
Double-tagging no longer causes an infinite loop. 
I am closing; this is working as intended.

**Closed by rosiel** 2023-02-27 15:26 UTC
Labels: bug
